/* export const metadata = {
  title: 'Wild Oasis',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
 */

import Logo from "./_components/logo";
import Navigation from "./_components/navigation";
import "@/app/_styles/globals.css";

export const metadata = {
    title: {
        template: "%s / The Wild Oasis",
        default: "Welcome / The Wild Oasis",
    },
    description:
        "Luxurious cabin hotel, located in the heart of the Italian Dolomites, surrounded by beautiful mountails and dark forests",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body class="text-gray-50 bg-black min-h-screen">
                <header>
                    <Logo />
                </header>
                <Navigation />
                <main>{children}</main>
                <footer>Copyright by the Wild Oasis</footer>
            </body>
        </html>
    );
}
