/* export const metadata = {
  title: 'Wild Oasis',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
 */

import Logo from "./components/logo";
import Navigation from "./components/navigation";

export const metadata = {
  title: "The Wild Oasis",

}



export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
              <header>
              <Logo/>
              </header>
                <Navigation />
                <main>{children}</main>
                <footer>Copyright by the Wild Oasis</footer>
            </body>
        </html>
    );
}
